application: bold-result-374
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
# Endpoints handler
- url: /_ah/spi/.*
  script: transaction_api.APPLICATION

- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

- url: /.*
  script: worker.app

libraries:
- name: webapp2
  version: "2.5.2"
- name: jinja2
  version: latest
- name: pycrypto
  version: latest
- name: endpoints
  version: 1.0